# Generated by Django 4.2.11 on 2024-05-26 08:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_search_vector_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_questio_search__e53742_gin'),
        ),
    ]
